NAME: 'deit_base_distilled_patch16_224.base.adam'

DATASET:
  TYPE: 'pedes'
  NAME: 'PA100k'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 224
  WIDTH: 224

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'deit_base_distilled_patch16_224'
#  TYPE: 'swin_s'
#  TYPE: 'resnet50'
#  TYPE: 'bninception'
#  TYPE: 'tresnetM'
#  TYPE: 'vit_s'
#  TYPE: 'vit_b'

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 32
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: True

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'